services:
  job-database:
    image: mysql:8
    container_name: job-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobDb
    ports:
      - "1234:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - job-network
    command: --bind-address=0.0.0.0  # Ensures MySQL listens on all interfaces
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$password"]
      interval: 10s
      retries: 5

  job-backend:
    image: saipranithswargam/my-image:latest
    container_name: job-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: job-database
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: jobDb
      DB_PORT: 3306
    depends_on:
      job-database:
        condition: service_healthy
    networks:
      - job-network
    command: ["npm", "run", "start"]

volumes:
  db_data:

networks:
  job-network: