services:
  job-database:
    image: mysql:8
    container_name: job-database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - job-network

  job-backend:
    build:
      context: .
    container_name: job-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: job-database
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: jobDb
      DB_PORT: 3306
    depends_on:
      - job-database
    networks:
      - job-network
    command: ["npm", "run", "start:wait"]

volumes:
  db_data:

networks:
  job-network:
